name: nothing
description: Nothing to do.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.3+0

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  dio: ^5.3.2
  permission_handler: ^11.0.0
  logging: ^1.2.0
  event_bus: ^2.0.0
  connectivity_plus: ^4.0.2
  provider: ^6.0.5
  #  photo_manager: ^2.8.1
  photo_manager: ^3.0.0-dev.2
  flutter_local_notifications: ^15.1.1
  extended_text: ^11.1.0
  hive: ^2.2.3
  device_info_plus: ^9.0.3
  time: ^2.1.3
  uuid: ^3.0.7
  flutter_displaymode: ^0.6.0
  url_launcher: ^6.1.14
  pull_to_refresh:
    git:
      url: https://github.com/andfaraway/flutter_pulltorefresh.git
  #  flutter_tts: ^3.2.2
  shared_preferences: ^2.2.1
  fluttertoast: ^8.2.2
  flutter_colors_border: ^0.0.3+2
  flutter_swiper_null_safety_flutter3: ^4.0.0
  um_share_plugin: ^0.0.2
  flutter_spinkit: ^5.2.0
  jpush_flutter: ^2.4.7
  device_info: ^2.0.3
  package_info: ^2.0.2
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.1
  image_gallery_saver: ^2.0.3
  flutter_easyloading: ^3.0.5
  qr_flutter: ^4.1.0
  flutter_native_image: ^0.0.6+1
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  modal_bottom_sheet: ^3.0.0-pre
  hive_flutter: ^1.1.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_svg: ^2.0.7
  wechat_assets_picker: ^8.7.1
  # 网络图片缓存
  cached_network_image: ^3.2.3
  photo_view: ^0.14.0
  flutter_cache_manager: ^3.3.1
  # 系统风格弹框
  adaptive_dialog: ^1.9.0+2
  dropdown_button2: ^2.3.9
  extended_image: ^8.1.1
  image_editor: ^1.3.0
  image: ^4.0.17
  live_photo_maker: ^0.0.3
  video_player: ^2.7.1
  fijkplayer:
    git:
      url: https://github.com/diegothucao/cfijkplayer.git
      ref: master
  just_audio: ^0.9.40
  just_audio_background: ^0.0.1-beta.13
  audio_session: ^0.1.21
  rxdart: ^0.27.7
  flutter_smart_dialog: ^4.9.4
  file_preview: ^1.1.8
  flutter_image_compress: ^2.0.4
  share_plus: ^7.1.0
  webview_flutter: ^4.2.4
  lpinyin: ^2.0.3
  animated_bottom_navigation_bar: ^1.2.0
  confetti: ^0.7.0
  extra_hittest_area: ^0.1.0

  dotted_border: ^2.0.0+3
  desktop_drop: ^0.4.3
  crypto: ^3.0.3

  flutter_native_splash: ^2.3.2
  salomon_bottom_bar: ^3.3.2
  flutter_keyboard_visibility: ^5.4.1

  lottie: ^2.6.0
  clay_containers: ^0.3.4

  geolocator: ^11.0.0

  quick_actions: ^1.0.7

  flutter_tetris:
    git:
      url: https://github.com/andfaraway/flutter-tetris.git

  google_fonts: ^6.2.0
  dio_log_interceptor: ^0.0.7

dependency_overrides:
  intl: ^0.18.1
  file: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.po
  flutter_lints: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/tab/
    - assets/lottie/

flutter_assets_generator:
  # Optional. Sets the directory of generated localization files. Provided value should be a valid path on lib dir. Default: generated
  output_dir: generated
  # Optional. Sets whether automatic monitoring of file changes. Default: true
  auto_detection: true
  # Optional. Sets file name conversion rules. Default: true
  named_with_parent: true
  # Optional. Sets the name for the generated localization file. Default: assets
  output_filename: assets
  # Optional. Sets the name for the generated localization class. Default: Assets
  class_name: R

flutter_intl:
  enabled: true

